upload single file feautre added

diff --git a/madarles/scripts/upload b/madarles/scripts/upload
--- a/madarles/scripts/upload
+++ b/madarles/scripts/upload
@@ -5,7 +5,6 @@ source ${self_dir}/utils.sh
 source ~pi/.params
 export DB
 
-
 remove() {
   sql "UPDATE files SET state=1 WHERE filename='$1'"
 }
@@ -30,28 +29,39 @@ if [ -z "$FTP" -o -z "$DIR" ];then
   exit -1
 fi
 
+upload_file() {
+    FILE=$1
+    MTIME=`stat "$FILE" --printf "%Y"`
+    NEWNAME=${PREFIX}`date --date=@$MTIME "+%Y%m%d_%H%M%S"`.mp4
+    echo "Uploading $FILE with new name $NEWNAME"
+    curl -s --tcp-nodelay -n -T $FILE ftp://$FTP/$NEWNAME && remove $FILE
+    if [ $? == 0 ];then
+        echo "Upload OK"
+        successful=$[ $successful +1 ]
+    else
+        echo "Upload FAILED"
+        failed=$[ $failed +1 ]
+    fi
+}
 
-findsort.py $DIR
-FILECOUNT=`filecount`
-echo "Found $FILECOUNT files to upload."
-slack_msg "Found $FILECOUNT files to upload."
 successful=0
 failed=0
-while [ `filecount` -gt 4 ]; do
-  FILE=`sql "SELECT filename FROM files WHERE state=0 ORDER BY mtime LIMIT 1"`
-  MTIME=`stat "$FILE" --printf "%Y"`
-  NEWNAME=${PREFIX}`date --date=@$MTIME "+%Y%m%d_%H%M%S"`.mp4
-  echo "Uploading $FILE with new name $NEWNAME"
-  curl -s --tcp-nodelay -n -T $FILE ftp://$FTP/$NEWNAME && remove $FILE
-  if [ $? == 0 ];then
-    echo "Upload OK"
-    successful=$[ $successful +1 ]
-  else
-    echo "Upload FAILED"
-    failed=$[ $failed +1 ]
-  fi
-done
-echo "Upload statistics: successful: $successful failed: $failed"
-slack_msg "Upload statistics: successful: $successful failed: $failed"
+if [ $# -gt 0 ];then
+    msg "Uploading $# files"
+    while [ -f $1 ];do
+        upload_file $1
+        shift
+    done
+else
+    findsort.py $DIR
+    FILECOUNT=`filecount`
+    msg "Found $FILECOUNT files to upload."
+    while [ `filecount` -gt 4 ]; do
+      FILE=`sql "SELECT filename FROM files WHERE state=0 ORDER BY mtime LIMIT 1"`
+      upload_file $FILE
+    done
+fi
+
+msg "Upload statistics: successful: $successful failed: $failed"
 rm $PIDFILE
 
